### ISSUE TITLE
hackbot should lock reposted link threads and post link to old thread

### ISSUE THREAD

**Issue by rubinovitz** [kern/hackbot#8]

**Comment by gsingh93** [comment]
My proposed changes here cover this: https://github.com/kern/hackbot/issues/9

**Comment by kern** [comment]
Facebook's ToS doesn't let apps post as the app itself on groups, but it can post on behalf of the authenticated user. This could be implemented by scanning the `link` fields of the post object, normalizing them, and comparing.

Even if this isn't automatic, `/redirect` should be an alias of `/thread` so we can post links to the relevant subgroup/original topic. That's a quick fix.

**Comment by kern** [comment]
This is getting implemented in #11.
